name: 1. Check for future games

on:
  schedule:
    # Runs everyday at 08:00 UTC (10:00 Belgian summer time)
    - cron: '0 8 * * *'
  workflow_dispatch: # To manually start

jobs:
  check-match:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write # Job has permissions to write to the variables
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pytz discord-webhook

      - name: Run match checker script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_BOT }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GH_REPO: ${{ github.repository }} # Built-in variable
        run: python check_match.py
