name: 2. Hourly score checker

on:
  schedule:
    # Draait elk uur, 5 minuten over het uur
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  send-score:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pytz discord-webhook

      - name: Run score sender script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_BOT }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: python send_score.py
